config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :campaigns do
    resources :campaigns_players
    resources :player_characters do
      put 'toggle_active', to: 'player_characters#toggle_active'
    end
    resources :nonplayer_characters
    resources :log_entries
    resources :locations
    get 'previously-on', to: 'log_entries#previously_on', as: :previously_on
  end

  root to: 'homepage#index'
end

app/models/player_character.rb
class PlayerCharacter < Character
  belongs_to :player, class_name: 'User', foreign_key: :player_id
  validates :player, presence: true
end

app/controllers/player_characters_controller.rb
class PlayerCharactersController < ApplicationController
  before_action :set_player_character, only: [:show, :edit, :update, :destroy]

  def index
    authorize @campaign, :show?

    @player_characters = @campaign.player_characters.alphabetical
  end

  def show
    authorize @player_character
  end

  def new
    @player_character = PlayerCharacter.new(campaign: @campaign)
    authorize @player_character
  end

  def create
    @player_character = PlayerCharacter.new(player_character_params)
    authorize @player_character

    if @player_character.save
      redirect_to campaign_player_character_path(@campaign, @player_character)
    else
      render :new
    end
  end

  def edit
    authorize @player_character
  end

  def update
    authorize @player_character

    if @player_character.update(player_character_params)
      redirect_to campaign_player_character_path(@campaign, @player_character)
    else
      render :edit
    end
  end

  def destroy
    authorize @player_character

    @player_character.destroy
    redirect_to root_path
  end

  def toggle_active
    authorize @campaign, :show?
    player_character = PlayerCharacter.find(params[:player_character_id])
    player_character.update(active: !player_character.active)
    redirect_to campaign_player_character_path(@campaign, player_character)
  end

  private

  def set_player_character
    @player_character = PlayerCharacter.find(params[:id])
  end

  def player_character_params
    params
      .require(:player_character)
      .permit(:name, :public_description, :campaign_id, :player_id, :avatar, :active)
  end
end

app/views/player_characters/_form.html.slim
= form_for [@campaign, player_character] do |f|
  = f.hidden_field :campaign_id

  .form-group
    = f.label :name, class: 'label'
    = f.text_field :name, class: 'form-control'

  .form-group
    .form-check
      = f.label :active, class: 'label' do
        = f.check_box :active, class: 'form-check-input'
        = Character.human_attribute_name(:active)

  .form-group
    = f.label :avatar, class: 'label'
    = f.hidden_field :avatar, value: player_character.cached_avatar_data
    = f.file_field :avatar

  .form-group
    = f.label :public_description, class: 'label'
    = f.text_area :public_description, class: 'form-control', rows: 20, data: { provider: 'summernote' }

  .form-group
    = f.label :player_id, class: 'label'
    = f.select :player_id, options_from_collection_for_select(@campaign.players, :id, :email, (player_character.player || current_user).id), {}, { class: 'form-control' }

  = f.submit 'Save', class: 'btn btn-success pull-right'
  = destroy_link_for player_character

app/views/player_characters/_player_character.html.slim
= render 'characters/character', character: player_character

app/views/player_characters/edit.html.slim
h1 = @player_character.name
= render 'form', player_character: @player_character

app/views/player_characters/index.html.slim
.row.mb-3
  .col-md-8
    h1 = 'Player Characters'
  .col-md-4
    .float-right.ml-2
      = link_to '+', new_campaign_player_character_path(@campaign), class: 'btn btn-success'

.row.mb-3
  - @player_characters.each do |character|
    .col-lg-3.col-md-4
      = render character

app/views/player_characters/new.html.slim
h1 = @player_character.name
= render 'form', player_character: @player_character

app/views/player_characters/show.html.slim
.row
  .col-md-3
    .d-flex.flex-column.align-items-center

      = image_tag @player_character.avatar_url(:small), class: 'avatar mb-3'
      h2.text-center.mb-3 = @player_character.name

    = edit_link_for(@player_character, nil, 'w-100 mb-2')

    - if @player_character.active
      = link_to 'Hide from campaign', campaign_player_character_toggle_active_path(@campaign, @player_character), method: :put, class: 'btn btn-danger w-100 mb-2'
    - else
      = link_to 'Show on campaign', campaign_player_character_toggle_active_path(@campaign, @player_character), method: :put, class: 'btn btn-success w-100 mb-2'

  .col-md-9
    = sanitize @player_character.public_description