config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :campaigns do
    resources :campaigns_players
    resources :player_characters do
      put 'toggle_active', to: 'player_characters#toggle_active'
    end
    resources :nonplayer_characters
    resources :log_entries
    resources :locations
    get 'previously-on', to: 'log_entries#previously_on', as: :previously_on
  end

  root to: 'homepage#index'
end

app/models/log_entry.rb
class LogEntry < ApplicationRecord
  belongs_to :campaign
  scope :ic_chronological, -> { order(ic_date: :asc) }
  scope :ic_anti_chronological, -> { order(ic_date: :desc) }
  scope :oc_anti_chronological, -> { order(oc_date: :desc) }

  after_save :update_campaign_date

  private

  def update_campaign_date
    campaign.update_current_date
  end
end

app/controllers/log_entries_controller.rb
class LogEntriesController < ApplicationController
  before_action :set_log_entry, only: [:show, :edit, :update, :destroy]

  def index
    authorize @campaign, :show?

    @log_entries = @campaign.log_entries.ic_anti_chronological.oc_anti_chronological
  end

  def previously_on
    @session = @campaign.log_entries.last.oc_date
    @log_entries = @campaign.log_entries.where(oc_date: @session).ic_chronological
  end

  def show
    authorize @log_entry
  end

  def new
    @log_entry = LogEntry.new(campaign: @campaign)
    authorize @log_entry

    @log_entry.ic_date = @campaign.current_date
    @log_entry.oc_date = Time.zone.today
  end

  def create
    @log_entry = LogEntry.new(log_entry_params)
    authorize @log_entry

    if @log_entry.save
      redirect_to campaign_log_entry_path(@campaign, @log_entry)
    else
      render :new
    end
  end

  def edit
    authorize @log_entry
  end

  def update
    authorize @log_entry

    if @log_entry.update(log_entry_params)
      redirect_to campaign_log_entry_path(@campaign, @log_entry)
    else
      render :edit
    end
  end

  def destroy
    authorize @log_entry

    @log_entry.destroy
    redirect_to campaign_log_entries_path(@campaign)
  end

  private

  def set_log_entry
    @log_entry = LogEntry.find(params[:id])
  end

  def log_entry_params
    params
      .require(:log_entry)
      .permit(:title, :text, :ic_date, :oc_date, :campaign_id)
  end
end

app/views/log_entries/_form.html.slim
= form_for [@campaign, log_entry] do |f|
  = f.hidden_field :campaign_id

  .form-group
    = f.label :title, class: 'label'
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :text, class: 'label'
    = f.text_area :text, class: 'form-control', rows: 20, data: { provider: 'summernote' }

  .form-group
    = f.label :oc_date, class: 'label'
    = f.date_field :oc_date, class: 'form-control'

  .form-group
    = f.label :ic_date, class: 'label'
    = f.date_field :ic_date, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-success pull-right'
  = destroy_link_for log_entry

app/views/log_entries/_log_entry.html.slim
= link_to campaign_log_entry_path(@campaign, log_entry) do
  .card.mb-3
    .card-body
      h3.card-title
        = log_entry.title
      h6.card-subtitle.muted.mb-2
        = to_absalom_reckoning(log_entry.ic_date)
      p.card-text
        = truncate(strip_tags(log_entry.text), length: 200)

app/views/log_entries/edit.html.slim
h1 = @log_entry.title
= render 'form', log_entry: @log_entry

app/views/log_entries/index.html.slim
.row.mb-3
  .col-md-8
    h1 = 'Log entries'
  .col-md-4
    .float-right
      = link_to '+', new_campaign_log_entry_path(@campaign), class: 'btn btn-success'

= render @log_entries

app/views/log_entries/new.html.slim
h1 = @log_entry.title
= render 'form', log_entry: @log_entry

app/views/log_entries/previously_on.html.slim
h1 = "Previously on #{@campaign.name}"
- @log_entries.each do |log_entry|
  .row.mb-3
    .col-md-3
      hr
      strong.float-right.mb-2 = to_absalom_reckoning(log_entry.ic_date)
    .col-md-9
      hr
      == log_entry.text

app/views/log_entries/show.html.slim
.row
  .col-md-3
    h1.text-center = @log_entry.title
    .mb-2
      strong = to_absalom_reckoning(@log_entry.ic_date)
    = link_to 'Edit log entry', edit_campaign_log_entry_path(@campaign, @log_entry), class: 'btn btn-info w-100 mb-2'
    = render 'shared/back_to', url: campaign_log_entries_path(@campaign), name: 'log entries'
  .col-md-9
    p = sanitize @log_entry.text