config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :campaigns do
    resources :campaigns_players
    resources :player_characters do
      put 'toggle_active', to: 'player_characters#toggle_active'
    end
    resources :nonplayer_characters
    resources :log_entries
    resources :locations
    get 'previously-on', to: 'log_entries#previously_on', as: :previously_on
  end

  root to: 'homepage#index'
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :player_characters
  has_many :nonplayer_characters
  has_many :locations
  has_many :log_entries

  has_many :campaigns_players, dependent: :destroy
  has_many :players, through: :campaigns_players, source: :user

  belongs_to :game_master, class_name: 'User', foreign_key: :game_master_id

  def update_current_date
    latest_log_date = log_entries.pluck(:ic_date).max
    update(current_date: latest_log_date) if latest_log_date
  end

  def member?(user)
    user.id == game_master_id || campaigns_players.pluck(:user_id).include?(user.id)
  end

  def members
    member_ids = players.pluck(:id) << game_master_id
    User.where(id: member_ids)
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update]

  def show
    authorize @campaign

    @locations = @campaign.locations.recent.limit(3)
    @log_entries = @campaign.log_entries.ic_anti_chronological.oc_anti_chronological.limit(5)
    @nonplayer_characters = @campaign.nonplayer_characters.recent.limit(3)
    @player_characters = @campaign.player_characters.active
  end

  def new
    @campaign = Campaign.new
    authorize @campaign
  end

  def create
    @campaign = Campaign.new(campaign_params)
    authorize @campaign

    @campaign.game_master = current_user

    if @campaign.save
      redirect_to @campaign
    else
      render :new
    end
  end

  def edit
    authorize @campaign

    @available_players = User.where.not(id: @campaign.members.pluck(:id))
  end

  def update
    authorize @campaign

    initial_gm = @campaign.game_master

    if @campaign.update(campaign_params)
      unless @campaign.game_master == initial_gm
        @campaign.players << initial_gm
        @campaign.campaigns_players.find_by(user_id: @campaign.game_master_id).destroy
      end

      redirect_to campaign_path(@campaign)
    else
      render :edit
    end
  end

  private

  def campaign_params
    params.require(:campaign).permit(:name, :game_master_id)
  end

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end
end

app/views/campaigns/_campaign.html.slim
= link_to campaign_path(campaign) do
  .card.mb-3
    .card-body
      h3.card-title = campaign.name

      p.card-text
        ul
          - player_list = campaign.players.map(&:email).each do |player|
            li = player
          - if player_list.empty?
            li = t('campaing.no_players')

    .card-footer
      small.text-muted
        => t('campaign.game_master')
        = campaign.game_master.email

app/views/campaigns/_form.html.slim
= form_for campaign do |f|
  .form-group
    = f.label :name, class: 'label'
    .row
      .col-sm-10
        = f.text_field :name, class: 'form-control'
      .col-sm-2
        = f.submit 'Save', class: 'btn btn-success col-xs-12'

app/views/campaigns/edit.html.slim
h1 Edit Campaign

= render 'form', campaign: @campaign

hr

h2 Your players
table.table.table-striped
  tr
    th Player
    th Remove from campaign
    th Transfer GM-ship
  - @campaign.players.each do |player|
    tr
      td = player
      td = destroy_link_for(CampaignsPlayer.find_by(user_id: player.id, campaign_id: @campaign.id))
      td = link_to 'Make this player the new GM', campaign_path(@campaign, campaign: { game_master_id: player.id }), method: :patch, data: { confirm: 'You will no longer be the GM. Are you sure?' }

hr

h2 Add players
- if @available_players.empty?
  p Players must register an account before they can be added to your campaign
- else
  = form_for [@campaign, CampaignsPlayer.new(campaign_id: @campaign.id)] do |f|
    .form-group
      = f.hidden_field :campaign_id
      = f.label :user, class: 'label'
      .row
        .col-sm-10
          = f.select :user_id, options_from_collection_for_select(@available_players, :id, :email), {}, { class: 'form-control' }
        .col-sm-2
          = f.submit 'Add this player', class: 'btn btn-success pull-right col-xs-12'

= destroy_link_for @campaign

app/views/campaigns/new.html.slim
h1 Start new Campaign

= render 'form', campaign: @campaign

= destroy_link_for @campaign

app/views/campaigns/show.html.slim
.row
  .col-lg-3.col-md-4.mb-3
    h2.mb-3
      = @campaign.name
      = edit_link_for(@campaign, t('general.edit'), 'float-right')

    = render @player_characters
    = link_to 'Add PC', new_campaign_player_character_path(@campaign), class: 'btn btn-success w-100 mb-2'
    = link_to 'All PCs', campaign_player_characters_path(@campaign), class: 'btn btn-info w-100 mb-2'
    = link_to 'NPCs', campaign_nonplayer_characters_path(@campaign), class: 'btn btn-info w-100 mb-2'
    = link_to 'Locations', campaign_locations_path(@campaign), class: 'btn btn-info w-100 mb-2'

  .col-lg-9.col-md-8.mb-3
    .row
    h2.mb-3
      = link_to 'Log entries', campaign_log_entries_path(@campaign)
      = link_to '+', new_campaign_log_entry_path(@campaign), class: 'btn btn-success float-right ml-2'
      = link_to 'Previously on', campaign_previously_on_path(@campaign), class: 'btn btn-info float-right'

    = render @log_entries
    = link_to 'More Log entries', campaign_log_entries_path(@campaign), class: 'btn btn-block btn-info'