config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :campaigns do
    resources :campaigns_players
    resources :player_characters do
      put 'toggle_active', to: 'player_characters#toggle_active'
    end
    resources :nonplayer_characters
    resources :log_entries
    resources :locations
    get 'previously-on', to: 'log_entries#previously_on', as: :previously_on
  end

  root to: 'homepage#index'
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :campaign
  belongs_to :area, class_name: 'Location', foreign_key: :location_id
  has_many :sections, class_name: 'Location', foreign_key: :location_id

  scope :recent, -> { order(updated_at: :desc) }
  scope :alphabetical, -> { order(name: :asc) }
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    authorize @campaign, :show?

    @locations = @campaign.locations.alphabetical
  end

  def show
    authorize @location
  end

  def new
    @location = Location.new(campaign: @campaign)
    authorize @location
  end

  def create
    @location = Location.new(location_params)
    authorize @location

    if @location.save
      redirect_to campaign_location_path(@campaign, @location)
    else
      render :new
    end
  end

  def edit
    authorize @location
  end

  def update
    authorize @location

    if @location.update(location_params)
      redirect_to campaign_location_path(@campaign, @location)
    else
      render :edit
    end
  end

  def destroy
    authorize @location

    @location.destroy
    redirect_to campaign_locations_path(@campaign)
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params
      .require(:location)
      .permit(:name, :public_description, :campaign_id)
  end
end

app/views/locations/_form.html.slim
= form_for [@campaign, location] do |f|
  = f.hidden_field :campaign_id

  .form-group
    = f.label :name, class: 'label'
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :public_description, class: 'label'
    = f.text_area :public_description, class: 'form-control', rows: 20, data: { provider: 'summernote' }

  = f.submit 'Save', class: 'btn btn-success pull-right'
  = destroy_link_for location

app/views/locations/_location.html.slim
= link_to campaign_location_path(@campaign, location) do
  .card.mb-3
    .card-body
      h3.card-title = location.name
      p.card-text = truncate(strip_tags(location.public_description), length: 200)

app/views/locations/edit.html.slim
h1 = @location.name
= render 'form', location: @location

app/views/locations/index.html.slim
.row.mb-3
  .col-md-8
    h1 = 'Locations'
  .col-md-4
    .float-right
      = link_to '+', new_campaign_location_path(@campaign), class: 'btn btn-success float-right'

= render @locations

app/views/locations/new.html.slim
h1 = @location.name
= render 'form', location: @location

app/views/locations/show.html.slim
.row
  .col-md-3
    h1.text-center = @location.name
    = link_to 'Edit location', edit_campaign_location_path(@campaign, @location), class: 'btn btn-info w-100 mb-2'
    = render 'shared/back_to', url: campaign_locations_path(@campaign), name: 'locations'
  .col-md-9

    p = sanitize @location.public_description